sudo: false
language: node_js
node_js:
  - "0.12"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g grunt-cli
  - npm install -g tsd
  - npm install -g bower
cache:
  directories:
    - bower_components
    - node_modules
    - typings
addons:
  apt:
    sources:
      - https://dl-ssl.google.com/linux/linux_signing_key.pub
    packages:
      - google-chrome-stable